"""Redis infrastructure."""

from __future__ import annotations

from .client import get_redis, ping_redis
from .keys import (
    quote_key,
    bars_latest_key,
    heartbeat_key,
    backtest_progress_key,
    broker_status_key,
    RISK_STATUS_KEY,
    STREAM_MARKET_TICKS,
    STREAM_MARKET_BARS,
    STREAM_NEWS,
    STREAM_AI_SIGNALS,
    STREAM_ORDERS,
    STREAM_RISK,
    STREAM_BACKTEST,
    STREAM_SYSTEM,
    QUEUE_NEWS_FETCH,
    QUEUE_NEWS_AI_ANALYZE,
    QUEUE_BACKTEST_RUN,
    QUEUE_AI_SIGNAL_SCAN,
    QUEUE_MARKET_CACHE_BARS,
    lock_news_crawl,
    lock_backtest,
    lock_order,
    lock_bars,
)
from .serialization import to_json, from_json
from .streams import xadd_json, ensure_consumer_group, read_group_json, ack
from .queues import (
    setup_dramatiq,
    NEWS_FETCH_QUEUE,
    NEWS_AI_ANALYZE_QUEUE,
    BACKTEST_RUN_QUEUE,
    AI_SIGNAL_SCAN_QUEUE,
    MARKET_CACHE_BARS_QUEUE,
)
from .locks import acquire_lock, release_lock, distributed_lock
from .heartbeat import write_heartbeat, read_heartbeat, get_service_status

__all__ = [
    "get_redis",
    "ping_redis",
    "quote_key",
    "bars_latest_key",
    "heartbeat_key",
    "backtest_progress_key",
    "broker_status_key",
    "RISK_STATUS_KEY",
    "STREAM_MARKET_TICKS",
    "STREAM_MARKET_BARS",
    "STREAM_NEWS",
    "STREAM_AI_SIGNALS",
    "STREAM_ORDERS",
    "STREAM_RISK",
    "STREAM_BACKTEST",
    "STREAM_SYSTEM",
    "QUEUE_NEWS_FETCH",
    "QUEUE_NEWS_AI_ANALYZE",
    "QUEUE_BACKTEST_RUN",
    "QUEUE_AI_SIGNAL_SCAN",
    "QUEUE_MARKET_CACHE_BARS",
    "lock_news_crawl",
    "lock_backtest",
    "lock_order",
    "lock_bars",
    "to_json",
    "from_json",
    "xadd_json",
    "ensure_consumer_group",
    "read_group_json",
    "ack",
    "setup_dramatiq",
    "NEWS_FETCH_QUEUE",
    "NEWS_AI_ANALYZE_QUEUE",
    "BACKTEST_RUN_QUEUE",
    "AI_SIGNAL_SCAN_QUEUE",
    "MARKET_CACHE_BARS_QUEUE",
    "acquire_lock",
    "release_lock",
    "distributed_lock",
    "write_heartbeat",
    "read_heartbeat",
    "get_service_status",
]
